[build]
  command = "npm run test:smoke && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."generateAuditionMaterials"]
  timeout = 26
  node_bundler = "esbuild"

[functions."lookupShowCast"]
  timeout = 26
  node_bundler = "esbuild"

[functions."lookupShowScenes"]
  timeout = 26
  node_bundler = "esbuild"

[functions."sendCheckinAlerts"]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
